server:
  port: 8081

elasticsearch:
  request:
    defaultQuerySize: 10
    defaultQueryPage: 0
    getAllSize: 50
  fields:
    name: name
    brand: brand
    nameShingles: name.shingles
    brandKeyword: brand.keyword
    price: price
    keyword: keyword
  aggregation:
    count: _count
    key: _key
    cheap: Cheap
    average: Average
    expensive: Expensive
    priceRanges: price_ranges
    brandCount: brand_count
    cheapPrice: 100.0
    expensivePrice: 500.0
  index:
    productIndex: product_index
    conceptIndex: concept_index
    searchTerms: search_terms
  nested:
    skus: skus
