elasticsearch:
  fields:
    name: name
    id: _id
    nameVector: name_vector
  property:
    esHost: ${ES_HOST:http://localhost:9200}
    user: ${ES_USER:}
    password: ${ES_PASS:}
  index:
    index: _index
    indexName: ${ES_INDEX:product_index}
    indicesAmount: ${ES_INDICES_COUNT:3}
  file:
    mappings: classpath:products/mappings.json
    settings: classpath:products/settings.json
    bulkData: classpath:products/bulk_data.txt
  openAI:
    embeddingModel: text-embedding-3-large